### ISSUE TITLE
any plan for implement org.apache.kafka.common.serialization.Serde

### ISSUE THREAD

**Issue by vehas** [ovotech/kafka-avro-confluent#2]
thank you for your project,
          this really help me in kafka producer and consumer. but I also want to use this with kafka stream which is implement **org.apache.kafka.common.serialization.Serde**.
so, Do you have any plan to support that ? or I can help you write that part, I just need some help for starting point.

**Comment by vise890-ovo** [comment]
Hi there,

I've pushed an implementation of `Serde` in the latest snapshot (`0.9.1-SNAPSHOT`), and updated the README with instructions on how to use it. Do you mind pulling it and testing it out?

Cheers,
M.

**Comment by vise890-ovo** [comment]
this has been inactive for a while. I'm closing it

See the discussion here for alternatives: https://github.com/ovotech/kafka-avro-confluent/pull/3#issuecomment-400242626
